"""initial schema

Revision ID: e01704cc2ebf
Revises:
Create Date: 2026-04-21 20:29:17.812559

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e01704cc2ebf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "firmwares",
        sa.Column("hardware", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("hardware", "kind", "version"),
    )
    with op.batch_alter_table("firmwares", schema=None) as batch_op:
        batch_op.create_index(
            "ix_firmwares_hardware_kind_timestamp",
            ["hardware", "kind", sa.literal_column("timestamp DESC")],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firmwares", schema=None) as batch_op:
        batch_op.drop_index("ix_firmwares_hardware_kind_timestamp")

    op.drop_table("firmwares")
    # ### end Alembic commands ###
